/// Unix error number errors
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnixErrorNumber {
    OperationNotPermitted = 1,
    NoSuchFileOrDirectory,
    NoSuchProcess,
    InterruptedSystemCall,
    InputOutputError,
    NoSuchDeviceOrAddress,
    ArgumentListTooLong,
    ExecutableFormatError,
    BadFileDescriptor,
    NoChildProcesses,
    ResourceTemporarilyUnavailable,
    CannotAllocateMemory,
    PermissionDenied,
    BadAddress,
    BlockDeviceRequired,
    DeviceOrResourceBusy,
    FileExists,
    InvalidCrossDeviceLink,
    NoSuchDevice,
    NotADirectory,
    IsADirectory,
    InvalidArgument,
    TooManyOpenFilesInSystem,
    TooManyOpenFiles,
    InappropriateIoCtlForDevice,
    TextFileBusy,
    FileTooLarge,
    NoSpaceLeftOnDevice,
    IllegalSeek,
    ReadOnlyFileSystem,
    TooManyLinks,
    BrokenPipe,
    NumericalArgumentOutOfDomain,
    NumericalResultOutOfRange,
    ResourceDeadlockAvoided,
    FileNameTooLong,
    NoLocksAvailable,
    FunctionNotImplemented,
    DirectoryNotEmpty,
    TooManyLevelsOfSymbolicLinks,
    NoMessageOfDesiredType = 0x2A,
    IdentifierRemoved,
    ChannelNumberOutOfRange,
    Level2NotSyncronized,
    Level3Halted,
    Level3Reset,
    LinkNumberOutOfRange,
    ProtocolDriverNotAttached,
    NoCSIStructureAvailable,
    Level2Halted,
    InvalidExchange,
    InvalidRequestDescriptor,
    ExchangeFull,
    NoANode,
    InvalidRequestCode,
    InvalidSlot,
    FileLockingDeadlockError,
    BadFontFileFormat,
    DeviceNotAStream,
    NoDataAvailable,
    TimerExpired,
    OutOfStreamsResources,
    MachineIsNotOnTheNetwork,
    PackageNotInstalled,
    ObjectIsRemote,
    LinkHasBeenSevered,
}

/// Syscall Result Type
pub type SyscallResult<T> = Result<T, UnixErrorNumber>;
